default: default
profiles:
  default:
    cmd: pi
    extensions:
      - mode
      - code-review
      - dynamic-skills
      - btw
      - loop
      - render-raw
    skills:
      - repo-explorer
    prompts:
      - overview
  reviewer:
    cmd: pi -p
    extensions: []
    prompts:
      - code-review
  review-agent-trajectory:
    cmd: pi -p
    prompts:
      - review-agent-trajectory
